
# VSCode Extensions
echo_title "Installing VSCode Extensions..."
code --install-extension be5invis.vscode-icontheme-nomo-dark
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension geddski.macros
code --install-extension michelemelluso.gitignore
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-duplicate
code --install-extension naumovs.color-highlight
code --install-extension patbenatar.advanced-new-file
code --install-extension pmndrs.pmndrs
code --install-extension ryuta46.multi-command
code --install-extension sdras.night-owl
code --install-extension sherloach.solarized-osaka
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-french
code --install-extension supermaven.supermaven
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vscode-icons-team.vscode-icons
code --install-extension whizkydee.material-palenight-theme
code --install-extension yoavbls.pretty-ts-errors